package:
  name: py-compressed-decoder
  version: "0.2.0"

source:
  git_url: ../..

build:
  number: 0

requirements:
  build:
    - python {{ python }}
    - setuptools
    - pybind11>=2.2
    - yaml-cpp
    - hdf5
    - boost
  run:
    - python
    - yaml-cpp
    - hdf5
    - boost