package:
  name: py-compressed-decoder
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'develop') }}

source:
  git_url: ../..

build:
  number: 0
  script: cd python && python setup.py install --single-version-externally-managed --record=record.txt
  #script: "cd python && {{ PYTHON }} -m pip install . --no-deps -vvv"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - pybind11>=2.2
    - yaml-cpp
    - hdf5
  run:
    - python
    - yaml-cpp
    - hdf5
