package:
  name: py-compressed-decoder
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ../..

build:
  number: 0
  script: cd python && python setup.py install --single-version-externally-managed --record=record.txt
  #script: "cd python && {{ PYTHON }} -m pip install . --no-deps -vvv"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - pybind11>=2.2
    - yaml-cpp==0.6.2
    - hdf5
    - boost
  run:
    - python
    - yaml-cpp==0.6.2
    - hdf5
    - boost
